version: '3.3'

services:
  database:
    image: mysql:5.7
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'somestrongpass'
      MYSQL_DATABASE: 'csci36'
      MYSQL_USER: 'csci36'
      MYSQL_PASSWORD: 'csci36'

  app:
    build: .
    ports:
      - "5000:5000"
    container_name: node_app
    links:
     - database:database
    environment:
      USERNAME: 'csci36'
      PASSWORD: 'csci36'
      DATABASE: 'csci36'
      DBHOST: 'database'
      PORT: '5000'
    depends_on:
      - database
    restart: on-failure

volumes:
  db_data: {}
